In [136]:
import numpy as np 
np.__version__

'2.1.3'

In [137]:
np?

Type:        module
String form: <module 'numpy' from '/Users/pranavrajan/miniconda3/envs/workbench/lib/python3.13/site-packages/numpy/__init__.py'>
File:        ~/miniconda3/envs/workbench/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three gr

In [138]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [139]:
type(L[0])

int

In [140]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [141]:
type(L2[0])

str

In [142]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [143]:
# fixed type arrays 
import array 
L = list(range(10))
A= array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
# integer array
np.array([1, 2, 4, 5, 3])

array([1, 2, 4, 5, 3])

In [145]:
# float array
np.array([3.1, 4, 2, 3])

array([3.1, 4. , 2. , 3. ])

In [146]:
# float 32 array
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [147]:
# nested lists to create multi dimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [148]:
# create a length 10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [149]:
# create a 3x5 floating point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
# create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [151]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [152]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [153]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [154]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1,(3, 3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [155]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [156]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [157]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [158]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [159]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [160]:
# seed for reproducibility 
np.random.seed(0)
x1 = np.random.randint(10, size=6) # 1-d array
x2 = np.random.randint(10, size=(3, 4)) # 2-d array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3-d array

In [161]:
print("x3 ndim: ", x3.ndim) # number of dimensions 
print("x3 shape: ", x3.shape) # size of dimensions
print("x3 size: ", x3.size) # size of the total array 
print("dtype: ", x3.dtype) # data type of the array 
print("itemsize:", x3.itemsize, "bytes") # the size (in bytes) of each array element 
print("nbytes:", x3.nbytes, "bytes") # the total size(in bytes) of the array

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64
itemsize: 8 bytes
nbytes: 480 bytes


In [162]:
print(f"x1: {x1}")
print(f"x1[0]: {x1[0]}")
print(f"x1[4]: {x1[4]}")

x1: [5 0 3 3 7 9]
x1[0]: 5
x1[4]: 7


In [163]:
print(f"x1[-1]: {x1[-1]}")
print(f"x1[-2]: {x1[-2]}")

x1[-1]: 9
x1[-2]: 7


In [164]:
print(f"x2: {x2}")

x2: [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [165]:
print(f"x2[0, 0]: {x2[0, 0]}")
print(f"x2[2, 0]: {x2[2, 0]}")
print(f"x2[2, -1]: {x2[2, -1]}")
x2[0, 0] = 12 
x2

x2[0, 0]: 3
x2[2, 0]: 1
x2[2, -1]: 7


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [166]:
x1[0] = 3.14159 # this will be truncated 
x1

array([3, 0, 3, 3, 7, 9])

In [167]:
# Array Slicing 

In [168]:
# 1-d arrays 

In [169]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
# first 5 elements 
x[:5] 

array([0, 1, 2, 3, 4])

In [171]:
# elements after index 5 
x[5:]

array([5, 6, 7, 8, 9])

In [172]:
# middle of array 
x[4:7]

array([4, 5, 6])

In [173]:
# every other element 
x[:: 2]

array([0, 2, 4, 6, 8])

In [174]:
# every other element starting at index 1 
x[1::2]

array([1, 3, 5, 7, 9])

In [175]:
# reverse list 
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [176]:
# reverse every other from index 5 
x[5::-2]

array([5, 3, 1])

In [177]:
# multidimensional arrays 

In [178]:
x2 

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [179]:
# two rows, 3 cols 
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [180]:
# all rows, every other col 
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [181]:
# reverse subarray dimensions 
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [182]:
# accessing array rows and cols 

In [183]:
# first col of x2 
print(x2[:, 0])

[12  7  1]


In [184]:
# first row of x2 
print(x2[0, :])

[12  5  2  4]


In [185]:
print(x2[0])

[12  5  2  4]


In [186]:
# subarray non copy view 

In [187]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [188]:
# 2 x 2 subarray 
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [189]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [190]:
# print updated matrix 
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [191]:
# array copying 

In [192]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [193]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)



[[42  5]
 [ 7  6]]


In [194]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [195]:
# array reshaping 

In [196]:
# put tthe numbers 1-9 in a 3x3 grid 
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [197]:
# convert a one-dimensional array into a two-dimensional row or col matrix 
x = np.array([1, 2, 3])

# row vector via reshape 
x.reshape((1, 3))

array([[1, 2, 3]])

In [198]:
# row vector via new axis 
x[np.newaxis, :]

array([[1, 2, 3]])

In [199]:
# col vector via reshape 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [200]:
# col vector via newaxis 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [201]:
# array concatenation and splitting 


In [202]:
# two arrays concatenation 
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [203]:
# three arrays concatenation 
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [204]:
# two dimensional array concatenation 
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis (rows)
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [205]:
# concatenate along the second axis (cols)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [206]:
# stacking 
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays 
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [207]:
# horizontally stack the arrays 
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [208]:
# splitting arrays 

In [209]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
# 3 splits - [0:3], [3:5], [5:]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [210]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [211]:
# vertical split 
upper, lower = np.vsplit(grid, [2])
print(upper)
print()
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [212]:
# horizontal split 
left, right = np.hsplit(grid, [2])
print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
