In [1]:
import numpy as np 
# check numpy version 
np.__version__

'1.26.4'

In [ ]:
# Basic Data Types 
result = 0
for i in range(100):
    result += 1
result

100

In [3]:
x = 4 
x = "4"
x

'4'

In [4]:
# Python Lists 
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
# Python Array
import array 
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Numpy Arrays

In [11]:
# integer array 
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [12]:
# float upcast
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [13]:
# nested lists result in multi-dimensional arrays
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.54495851, 0.92565068, 0.61719964],
       [0.61842699, 0.42750075, 0.17625122],
       [0.13209538, 0.28372506, 0.05326552]])

In [21]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.667514  , -0.33365317, -0.50170004],
       [-2.44006133, -0.47251581, -1.22068467],
       [ 0.22266871,  0.72487276,  1.8022542 ]])

In [22]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[7, 5, 7],
       [0, 2, 7],
       [3, 7, 7]])

In [23]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [25]:
# string data types
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [26]:
# numpy standard data types 
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [27]:
print(f"Boolean")
print(np.zeros(10, dtype=np.bool_))
print(f"Default integer type - C Long = int64")
print(np.zeros(10, dtype=np.int_))
print(f"C int = int32")
print(np.zeros(10, dtype=np.intc))
print(f"Integer for indexing")
print(np.zeros(10, dtype=np.intp))
print("Byte-int8")
print(np.zeros(10, dtype=np.int8))
print("Integer-int16")
print(np.zeros(10, dtype=np.int16))
print("Integer-int32")
print(np.zeros(10, dtype=np.int32))
print("Integer-int64")
print(np.zeros(10, dtype=np.int64))
print("Unsigned Integer-uint8")
print(np.zeros(10, dtype=np.uint8))
print("Unsigned Integer-uint16")
print(np.zeros(10, dtype=np.uint16))
print("Unsigned Integer-uint32")
print(np.zeros(10, dtype=np.uint32))
print("Unsigned Integer-uint64")
print(np.zeros(10, dtype=np.uint64))
print("shorthand for float64")
print(np.zeros(10, dtype=np.float_))
print("Half precision float-float16")
print(np.zeros(10, dtype=np.float16))
print("Single precision float-float32")
print(np.zeros(10, dtype=np.float32))
print("Double precision float-float64")
print(np.zeros(10, dtype=np.float64))
print("shorthand for complex128")
print(np.zeros(10, dtype=np.complex_))
print("Complex Number-complex64 = 2 32-bit floats")
print(np.zeros(10, dtype=np.complex64))
print("Complex Number-complex128 = 2 64-bit floats")
print(np.zeros(10, dtype=np.complex128))


Boolean
[False False False False False False False False False False]
Default integer type - C Long = int64
[0 0 0 0 0 0 0 0 0 0]
C int = int32
[0 0 0 0 0 0 0 0 0 0]
Integer for indexing
[0 0 0 0 0 0 0 0 0 0]
Byte-int8
[0 0 0 0 0 0 0 0 0 0]
Integer-int16
[0 0 0 0 0 0 0 0 0 0]
Integer-int32
[0 0 0 0 0 0 0 0 0 0]
Integer-int64
[0 0 0 0 0 0 0 0 0 0]
Unsigned Integer-uint8
[0 0 0 0 0 0 0 0 0 0]
Unsigned Integer-uint16
[0 0 0 0 0 0 0 0 0 0]
Unsigned Integer-uint32
[0 0 0 0 0 0 0 0 0 0]
Unsigned Integer-uint64
[0 0 0 0 0 0 0 0 0 0]
shorthand for float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Half precision float-float16
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Single precision float-float32
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Double precision float-float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
shorthand for complex128
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
Complex Number-complex64 = 2 32-bit floats
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
Complex Number-