In [31]:
import numpy as np 

In [32]:
# integer list 
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
# check L element type
type(L[0])

int

In [34]:
# string list 
L2 = [str(c) for c in L]
L2 

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [35]:
# check L2 element type 
type(L2[0])

str

In [36]:
# mix type list 
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [37]:
# fix type arrays in python 
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# integer array
np.array([1, 2, 4, 5, 3])

array([1, 2, 4, 5, 3])

In [39]:
# float array
np.array([3.1, 4, 2, 3])

array([3.1, 4. , 2. , 3. ])

In [40]:
# float 32 array
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [41]:
# multi-dimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [42]:
# create a length 10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [45]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.52514969, 0.58577604, 0.00653301],
       [0.02406496, 0.1867111 , 0.78418021],
       [0.33929831, 0.56146365, 0.47303741]])

In [48]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.31827919,  0.376053  , -0.93882112],
       [-0.20871421, -0.03261433,  0.75807892],
       [-0.98376776,  0.76821022, -0.17615392]])

In [49]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 7, 4],
       [5, 2, 4],
       [7, 4, 9]])

In [50]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [ ]:
# numpy standard data types example using strings 
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
# numpy standard data types example using numpy object 
np.zeros(10, dtype=np.int16)