In [58]:
import numpy as np 

In [59]:
# seed for reproducibility
np.random.seed(0)  

# One-dimensional array
x1 = np.random.randint(10, size=6)  

# Two-dimensional array
x2 = np.random.randint(10, size=(3, 4)) 

# Three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  

In [60]:
# number of dimensions 
print("x3 ndim: ", x3.ndim) 

# size of dimensions
print("x3 shape: ", x3.shape) 

# size of the total array 
print("x3 size: ", x3.size) 

# data type of the array 
print("dtype: ", x3.dtype) 

# the size (in bytes) of each array element 
print("itemsize:", x3.itemsize, "bytes") 

# the total size(in bytes) of the array
print("nbytes:", x3.nbytes, "bytes") 

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64
itemsize: 8 bytes
nbytes: 480 bytes


In [61]:
# one-dimensional array 

# whole list 
print(x1)
print()

# first element 
print(x1[0])
print()

# ith element 
print(x1[4])
print()

# last element 
print(x1[-1])
print()

# ith last element 
print(x1[-2])

[5 0 3 3 7 9]

5

7

9

7


In [62]:
# multi-dimensional arrays 
print(x2)
print()

# print various elements 
print(x2[0, 0])
print()

print(x2[2, 0])
print()

print(x2[2, -1])
print()

# modify values 
x2[0, 0] = 12
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

3

1

7

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [63]:
# precision trunkation 
# this will be truncated!
x1[0] = 3.14159 
print(x1)

[3 0 3 3 7 9]


In [64]:
# one-dimensional array slicing 
x = np.arange(10)

# whole list 
print(x)
print()

# first five elements 
print(x[:5])
print()

# elements after index 5 
print(x[5:])
print()

# middle subarray 
print(x[4:7])
print()

# every other element
print(x[::2])
print()

# every other element starting at index 1 
print(x[1::2])


[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4]

[5 6 7 8 9]

[4 5 6]

[0 2 4 6 8]

[1 3 5 7 9]


In [65]:
# multi-dimensional array slicing 
print(x2)
print()

# two rows, 3 cols 
print(x2[:2, :3])
print()

# all rows, every other col 
print(x2[:3, ::2])
print()

# reverse subarray dimensions
print(x2[::-1, ::-1])
print()

# x2 first col 
print(x2[:, 0])
print()

# x2 first row 
print(x2[0, :])
print()

# first row compact syntax 
print(x2[0])

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

[[12  5  2]
 [ 7  6  8]]

[[12  2]
 [ 7  8]
 [ 1  7]]

[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]

[12  7  1]

[12  5  2  4]

[12  5  2  4]


In [66]:
# subarrays no-copy view 

# x2 original 
print(x2)
print()

# subarray of x2 
x2_sub = x2[:2, :2]
print(x2_sub)
print()

# modify subarray 
x2_sub[0, 0] = 99
print(x2_sub)
print()

# modify x2 
print(x2)
print()

# array copy 
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
print()

# modify array copy 
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print()

# x2 
print(x2)


[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

[[12  5]
 [ 7  6]]

[[99  5]
 [ 7  6]]

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

[[99  5]
 [ 7  6]]

[[42  5]
 [ 7  6]]

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [67]:
# array reshaping 

# reshape 1-9 into a 3x3 grid 
grid = np.arange(1, 10).reshape((3, 3))
print(grid)
print()

# reshape a one-dimensional array into a two dimensional row or column matrix 
x = np.array([1, 2, 3])
print()

# row vector via reshape
print(x.reshape((1, 3)))
print()

# row vector via newaxis
print(x[np.newaxis, :])
print()

# column vector via reshape
print(x.reshape((3, 1)))
print()

# column vector via newaxis
print(x[:, np.newaxis])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]]

[[1 2 3]]

[[1]
 [2]
 [3]]

[[1]
 [2]
 [3]]


In [68]:
# one dimensional array concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]

# two array concatenation 
print(np.concatenate([x, y]))
print()

# three array concatenation 
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1]

[ 1  2  3  3  2  1 99 99 99]


In [69]:
# multi-dimensional array concatenation 
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along axis=0 (rows)
np.concatenate([grid, grid])
print()

# concatenate along axis=1 (cols)
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# stacking 
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
print()

# vertically stack the arrays
print(np.vstack([x, grid]))
print()

# horizontally stack the arrays
y = np.array([[99],
              [99]])
print(np.hstack([grid, y]))



[[1 2 3]
 [9 8 7]
 [6 5 4]]

[[ 9  8  7 99]
 [ 6  5  4 99]]


In [71]:
# one-dimensional splitting arrays 
x = [1, 2, 3, 99, 99, 3, 2, 1]

# 3 splits - [0:3], [3:5], [5:]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [74]:
# multi-dimensional splitting arrays 
grid = np.arange(16).reshape((4, 4))
print(grid)
print()

# veritcal split 
upper, lower = np.vsplit(grid, [2])
print(upper)
print()
print(lower)
print()

# horizontal split 
left, right = np.hsplit(grid, [2])
print(left)
print()
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
