In [11]:
import numpy as np 

In [12]:
# compute the reciprocals for random integers 
np.random.seed(0)
values = np.random.randint(1, 10, size=5)

"""compute the reciprocals of a list of numbers"""
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output 

compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [13]:
# compute reciprocals 
print(compute_reciprocals(values))

# compute reciprocals vectorized 
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [14]:
# timing computing_reciprocals with standard function 
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

647 ms ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
# timing computing reciprocals with ufuncs and vectorized operations 
%timeit (1.0 / big_array)

706 μs ± 15.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [18]:
# ufuncs examples 

# one dimensional array 
print(np.arange(5) / np.arange(1, 6))
print()

# multi-dimensional array 
x = np.arange(9).reshape((3, 3))
print(2 ** x)
print()

# arithmetic 
x = np.arange(4)
print("x     =", x)
print()
print("x + 5 =", x + 5)
print()
print("x - 5 =", x - 5)
print()
print("x * 2 =", x * 2)
print()
print("x / 2 =", x / 2)
print()
print("x // 2 =", x // 2)  
print()
print("-x     = ", -x)
print()
print("x ** 2 = ", x ** 2)
print()
print("x % 2  = ", x % 2)
print()

# order of operations 
print(-(0.5*x + 1) ** 2)
print()

# operator functions example
np.add(x, 2)

[0.         0.5        0.66666667 0.75       0.8       ]

[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]

x     = [0 1 2 3]

x + 5 = [5 6 7 8]

x - 5 = [-5 -4 -3 -2]

x * 2 = [0 2 4 6]

x / 2 = [0.  0.5 1.  1.5]

x // 2 = [0 0 1 1]

-x     =  [ 0 -1 -2 -3]

x ** 2 =  [0 1 4 9]

x % 2  =  [0 1 0 1]

[-1.   -2.25 -4.   -6.25]



array([2, 3, 4, 5])

In [ ]:
# absolute value 
x = np.array([-2, -1, 0, 1, 2])

# python absolute value 
print(abs(x))
print()

# numpy absolute value 
print(np.absolute(x))
print()
print(np.abs(x))
print()

# complex absolute value 
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(np.abs(x))


[2 1 0 1 2]

[2 1 0 1 2]

[2 1 0 1 2]

[5. 5. 2. 1.]


In [22]:
# trig functions 
theta = np.linspace(0, np.pi, 3)

# trig functions 
print("theta      = ", theta)
print()
print("sin(theta) = ", np.sin(theta))
print()
print("cos(theta) = ", np.cos(theta))
print()
print("tan(theta) = ", np.tan(theta))
print()

# inverse trig functions 
x = [-1, 0, 1]
print("x         = ", x)
print()
print("arcsin(x) = ", np.arcsin(x))
print()
print("arccos(x) = ", np.arccos(x))
print()
print("arctan(x) = ", np.arctan(x))



theta      =  [0.         1.57079633 3.14159265]

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]

cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]

tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]

x         =  [-1, 0, 1]

arcsin(x) =  [-1.57079633  0.          1.57079633]

arccos(x) =  [3.14159265 1.57079633 0.        ]

arctan(x) =  [-0.78539816  0.          0.78539816]


In [24]:
# logarithms and exponents 

# exponentials 
x = [1, 2, 3]
print("x     =", x)
print()
print("e^x   =", np.exp(x))
print()
print("2^x   =", np.exp2(x))
print()
print("3^x   =", np.power(3, x))

# logarithms 
x = [1, 2, 4, 10]
print("x        =", x)
print()
print("ln(x)    =", np.log(x))
print()
print("log2(x)  =", np.log2(x))
print()
print("log10(x) =", np.log10(x))
print()

# precision logarithms 
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print()
print("log(1 + x) =", np.log1p(x))


x     = [1, 2, 3]

e^x   = [ 2.71828183  7.3890561  20.08553692]

2^x   = [2. 4. 8.]

3^x   = [ 3  9 27]
x        = [1, 2, 4, 10]

ln(x)    = [0.         0.69314718 1.38629436 2.30258509]

log2(x)  = [0.         1.         2.         3.32192809]

log10(x) = [0.         0.30103    0.60205999 1.        ]

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]

log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [32]:
# special ufuncs 
# these are located in scipy import special 
from scipy import special 

In [27]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print()
print("ln|gamma(x)| =", special.gammaln(x))
print()
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]

ln|gamma(x)| = [ 0.          3.17805383 12.80182748]

beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [ ]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print()
print("erfc(x) =", special.erfc(x))
print()
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]

erfc(x) = [1.         0.67137324 0.32219881 0.15729921]

erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [30]:
# advaned ufuncs 

# specifying output 
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)
print()
# array views 
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)
print()

# aggregation 

# reduce 
x = np.arange(1, 6)
print(np.add.reduce(x))
print()

# multiply 
print(np.multiply.reduce(x))
print()

# accumulate (intermediate values)
print(np.add.accumulate(x))
print()
print(np.multiply.accumulate(x))
print()

[ 0. 10. 20. 30. 40.]

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]

15

120

[ 1  3  6 10 15]

[  1   2   6  24 120]



In [31]:
# outer products 
x = np.arange(1, 6)
np.multiply.outer(x, x)

# create multiplication table 
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])